name: minichat
description: "A Flutter chat client for LLMs with OpenAI-compatible APIs, featuring local speech recognition via Whisper."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  gpt_markdown: ^1.1.7
  flutter_math_fork: ^0.7.4
  shared_preferences: ^2.5.5
  simple_sse_http: ^1.0.0
  simple_sse: ^2.0.0
  sherpa_onnx: ^1.13.3
  record: ^7.1.1
  archive: ^4.0.9
  path_provider: ^2.1.6
  path: ^1.9.1
  http: ^1.6.0
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
    - family: Silkscreen
      fonts:
        - asset: fonts/Silkscreen-Regular.ttf
